// Copyright (C) 2009-2021, Panagiotis Christopoulos Charitos and contributors.
// All rights reserved.
// Code licensed under the BSD License.
// http://www.anki3d.org/LICENSE

ANKI_RENDERER_OBJECT_DEF(GBuffer, gbuffer)
ANKI_RENDERER_OBJECT_DEF(GBufferPost, gbufferPost)
ANKI_RENDERER_OBJECT_DEF(ShadowMapping, shadowMapping)
ANKI_RENDERER_OBJECT_DEF(LightShading, lightShading)
ANKI_RENDERER_OBJECT_DEF(ForwardShading, forwardShading)
ANKI_RENDERER_OBJECT_DEF(LensFlare, lensFlare)
ANKI_RENDERER_OBJECT_DEF(Tonemapping, tonemapping)
ANKI_RENDERER_OBJECT_DEF(Bloom, bloom)
ANKI_RENDERER_OBJECT_DEF(FinalComposite, finalComposite)
ANKI_RENDERER_OBJECT_DEF(Dbg, dbg)
ANKI_RENDERER_OBJECT_DEF(ProbeReflections, probeReflections)
ANKI_RENDERER_OBJECT_DEF(DownscaleBlur, downscaleBlur)
ANKI_RENDERER_OBJECT_DEF(VolumetricFog, volumetricFog)
ANKI_RENDERER_OBJECT_DEF(DepthDownscale, depthDownscale)
ANKI_RENDERER_OBJECT_DEF(TemporalAA, temporalAA)
ANKI_RENDERER_OBJECT_DEF(UiStage, uiStage)
ANKI_RENDERER_OBJECT_DEF(Ssr, ssr)
ANKI_RENDERER_OBJECT_DEF(VolumetricLightingAccumulation, volumetricLightingAccumulation)
ANKI_RENDERER_OBJECT_DEF(IndirectDiffuseProbes, indirectDiffuseProbes)
ANKI_RENDERER_OBJECT_DEF(GenericCompute, genericCompute)
ANKI_RENDERER_OBJECT_DEF(ShadowmapsResolve, shadowmapsResolve)
ANKI_RENDERER_OBJECT_DEF(RtShadows, rtShadows)
ANKI_RENDERER_OBJECT_DEF(AccelerationStructureBuilder, accelerationStructureBuilder)
ANKI_RENDERER_OBJECT_DEF(MotionVectors, motionVectors)
ANKI_RENDERER_OBJECT_DEF(ClusterBinning, clusterBinning)
ANKI_RENDERER_OBJECT_DEF(Scale, scale)
ANKI_RENDERER_OBJECT_DEF(IndirectDiffuse, indirectDiffuse)
ANKI_RENDERER_OBJECT_DEF(VrsSriGeneration, vrsSriGeneration)
