---@meta

-- AnKi engine Lua scripting API.
-- AUTO GENERATED by AnKi/Script/LuaDefsGen.py from the binding XML.
-- This file is only consumed by the Lua Language Server; do not load it at runtime.

---@class LightComponentType
---@field kPoint integer
---@field kSpot integer
---@field kDirectional integer
LightComponentType = {}

---@class BodyComponentCollisionShapeType
---@field kFromMeshComponent integer
---@field kAabb integer
---@field kSphere integer
---@field kCount integer
BodyComponentCollisionShapeType = {}

---@class JointComponentyType
---@field kPoint integer
---@field kHinge integer
---@field kCount integer
JointComponentyType = {}

---@class ParticleGeometryType
---@field kQuad integer
---@field kMeshComponent integer
ParticleGeometryType = {}

---@class SkyboxComponentType
---@field kSolidColor integer
---@field kImage2D integer
---@field kGenerated integer
SkyboxComponentType = {}

---@class MeshComponentType
---@field kMeshResource integer
---@field kPrimitive integer
MeshComponentType = {}

---@class MeshComponentPrimitiveType
---@field kBox integer
---@field kSphere integer
MeshComponentPrimitiveType = {}

---@class ReparentFlag
---@field kNone integer
---@field kKeepWorldTransform integer
ReparentFlag = {}

---@class WeakArraySceneNodePtr
WeakArraySceneNodePtr = {}

---@return number
function WeakArraySceneNodePtr:getSize() end

---@param num number
---@return SceneNode
function WeakArraySceneNodePtr:getAt(num) end

---@class SceneComponentUpdateInfo
SceneComponentUpdateInfo = {}

---@return SceneNode
function SceneComponentUpdateInfo:getSceneNode() end

---@return number
function SceneComponentUpdateInfo:getDt() end

---@return number
function SceneComponentUpdateInfo:getPreviousTime() end

---@return number
function SceneComponentUpdateInfo:getCurrentTime() end

---@class LightComponent
LightComponent = {}

---@param lightComponentType integer
function LightComponent:setLightComponentType(lightComponentType) end

---@param vec4 Vec4
function LightComponent:setDiffuseColor(vec4) end

---@return Vec4
function LightComponent:getDiffuseColor() end

---@param num number
function LightComponent:setRadius(num) end

---@return number
function LightComponent:getRadius() end

---@param num number
function LightComponent:setDistance(num) end

---@return number
function LightComponent:getDistance() end

---@param num number
function LightComponent:setInnerAngle(num) end

---@return number
function LightComponent:getInnerAngle() end

---@param num number
function LightComponent:setOuterAngle(num) end

---@return number
function LightComponent:getOuterAngle() end

---@param b boolean
function LightComponent:setShadowEnabled(b) end

---@return boolean
function LightComponent:getShadowEnabled() end

---@class DecalComponent
DecalComponent = {}

---@param str string
---@return DecalComponent
function DecalComponent:setDiffuseImageFilename(str) end

---@return string
function DecalComponent:getDiffuseImageFilename() end

---@param num number
---@return DecalComponent
function DecalComponent:setDiffuseBlendFactor(num) end

---@return number
function DecalComponent:getDiffuseBlendFactor() end

---@param str string
---@return DecalComponent
function DecalComponent:setRoughnessMetalnessImageFilename(str) end

---@return string
function DecalComponent:getRoughnessMetalnessImageFilename() end

---@param num number
---@return DecalComponent
function DecalComponent:setRoughnessMetalnessBlendFactor(num) end

---@return number
function DecalComponent:getRoughnessMetalnessBlendFactor() end

---@class LensFlareComponent
LensFlareComponent = {}

---@param str string
function LensFlareComponent:loadImageResource(str) end

---@param vec2 Vec2
function LensFlareComponent:setFirstFlareSize(vec2) end

---@param vec4 Vec4
function LensFlareComponent:setColorMultiplier(vec4) end

---@class BodyComponent
BodyComponent = {}

---@param bodyComponentCollisionShapeType integer
function BodyComponent:setCollisionShapeType(bodyComponentCollisionShapeType) end

---@param vec3 Vec3
function BodyComponent:setBoxExtend(vec3) end

---@return Vec3
function BodyComponent:getBoxExtend() end

---@param num number
function BodyComponent:setSphereRadius(num) end

---@return number
function BodyComponent:getSphereRadius() end

---@class JointComponent
JointComponent = {}

---@param jointComponentyType integer
function JointComponent:setJointType(jointComponentyType) end

---@return integer
function JointComponent:getJointType() end

---@param vec3 Vec3
function JointComponent:setPivot1Origin(vec3) end

---@return Vec3
function JointComponent:getPivot1Origin() end

---@param vec3 Vec3
function JointComponent:setPivot2Origin(vec3) end

---@return Vec3
function JointComponent:getPivot2Origin() end

---@param mat3 Mat3
function JointComponent:setPivot1Rotation(mat3) end

---@return Mat3
function JointComponent:getPivot1Rotation() end

---@param mat3 Mat3
function JointComponent:setPivot2Rotation(mat3) end

---@return Mat3
function JointComponent:getPivot2Rotation() end

function JointComponent:movePivot1ToPivot2() end

function JointComponent:movePivot2ToPivot1() end

---@class TriggerComponent
TriggerComponent = {}

---@return WeakArraySceneNodePtr
function TriggerComponent:getSceneNodesEnter() end

---@return WeakArraySceneNodePtr
function TriggerComponent:getSceneNodesExit() end

---@class FogDensityComponent
FogDensityComponent = {}

---@param num number
function FogDensityComponent:setDensity(num) end

---@return number
function FogDensityComponent:getDensity() end

---@class CameraComponent
CameraComponent = {}

---@param num number
---@param num2 number
---@param num3 number
---@param num4 number
function CameraComponent:setPerspective(num, num2, num3, num4) end

---@class GlobalIlluminationProbeComponent
GlobalIlluminationProbeComponent = {}

---@param num number
function GlobalIlluminationProbeComponent:setCellSize(num) end

---@return number
function GlobalIlluminationProbeComponent:getCellSize() end

---@param num number
function GlobalIlluminationProbeComponent:setFadeDistance(num) end

---@return number
function GlobalIlluminationProbeComponent:getFadeDistance() end

---@class ReflectionProbeComponent
ReflectionProbeComponent = {}

---@class ParticleEmitter2Component
ParticleEmitter2Component = {}

---@param str string
---@return ParticleEmitter2Component
function ParticleEmitter2Component:setParticleEmitterFilename(str) end

---@return string
function ParticleEmitter2Component:getParticleEmitterFilename() end

---@param particleGeometryType integer
---@return ParticleEmitter2Component
function ParticleEmitter2Component:setParticleGeometryType(particleGeometryType) end

---@return integer
function ParticleEmitter2Component:getParticleGeometryType() end

---@class MeshComponent
MeshComponent = {}

---@param meshComponentType integer
---@return MeshComponent
function MeshComponent:setMeshComponentType(meshComponentType) end

---@param meshComponentPrimitiveType integer
---@return MeshComponent
function MeshComponent:setMeshComponentPrimitiveType(meshComponentPrimitiveType) end

---@param num number
---@return MeshComponent
function MeshComponent:setSpherePrimitiveSubdivision(num) end

---@param str string
---@return MeshComponent
function MeshComponent:setMeshFilename(str) end

---@class MaterialComponent
MaterialComponent = {}

---@param str string
---@return MaterialComponent
function MaterialComponent:setMaterialFilename(str) end

---@param num number
---@return MaterialComponent
function MaterialComponent:setSubmeshIndex(num) end

---@class SkinComponent
SkinComponent = {}

---@param str string
---@return SkinComponent
function SkinComponent:setSkeletonFilename(str) end

---@class SkyboxComponent
SkyboxComponent = {}

---@param skyboxComponentType integer
---@return SkyboxComponent
function SkyboxComponent:setSkyboxComponentType(skyboxComponentType) end

---@return integer
function SkyboxComponent:getSkyboxComponentType() end

---@param vec3 Vec3
---@return SkyboxComponent
function SkyboxComponent:setSkySolidColor(vec3) end

---@return Vec3
function SkyboxComponent:getSkySolidColor() end

---@param str string
---@return SkyboxComponent
function SkyboxComponent:setSkyImageFilename(str) end

---@param vec3 Vec3
---@return SkyboxComponent
function SkyboxComponent:setSkyImageColorBias(vec3) end

---@param vec3 Vec3
---@return SkyboxComponent
function SkyboxComponent:setSkyImageColorScale(vec3) end

---@param num number
---@return SkyboxComponent
function SkyboxComponent:setMinFogDensity(num) end

---@param num number
---@return SkyboxComponent
function SkyboxComponent:setMaxFogDensity(num) end

---@param num number
---@return SkyboxComponent
function SkyboxComponent:setHeightOfMinFogDensity(num) end

---@param num number
---@return SkyboxComponent
function SkyboxComponent:setHeightOfMaxFogDensity(num) end

---@param vec3 Vec3
---@return SkyboxComponent
function SkyboxComponent:setFogDiffuseColor(vec3) end

---@class SceneNode
SceneNode = {}

---@return string
function SceneNode:getName() end

---@param sceneNode SceneNode
---@param reparentFlag integer
function SceneNode:setParent(sceneNode, reparentFlag) end

function SceneNode:markForDeletion() end

---@param vec3 Vec3
function SceneNode:setLocalOrigin(vec3) end

---@return Vec3
function SceneNode:getLocalOrigin() end

---@param mat3 Mat3
function SceneNode:setLocalRotation(mat3) end

---@return Mat3
function SceneNode:getLocalRotation() end

---@param vec3 Vec3
function SceneNode:setLocalScale(vec3) end

---@return Vec3
function SceneNode:getLocalScale() end

---@param transform Transform
function SceneNode:setLocalTransform(transform) end

---@return Transform
function SceneNode:getLocalTransform() end

---@return LightComponent
function SceneNode:newLightComponent() end

---@return LensFlareComponent
function SceneNode:newLensFlareComponent() end

---@return DecalComponent
function SceneNode:newDecalComponent() end

---@return TriggerComponent
function SceneNode:newTriggerComponent() end

---@return FogDensityComponent
function SceneNode:newFogDensityComponent() end

---@return CameraComponent
function SceneNode:newCameraComponent() end

---@return GlobalIlluminationProbeComponent
function SceneNode:newGlobalIlluminationProbeComponent() end

---@return ReflectionProbeComponent
function SceneNode:newReflectionProbeComponent() end

---@return BodyComponent
function SceneNode:newBodyComponent() end

---@return ParticleEmitter2Component
function SceneNode:newParticleEmitter2Component() end

---@return MeshComponent
function SceneNode:newMeshComponent() end

---@return MaterialComponent
function SceneNode:newMaterialComponent() end

---@return SkinComponent
function SceneNode:newSkinComponent() end

---@return SkyboxComponent
function SceneNode:newSkyboxComponent() end

---@return JointComponent
function SceneNode:newJointComponent() end

---@return LightComponent
function SceneNode:getFirstLightComponent() end

---@return LensFlareComponent
function SceneNode:getFirstLensFlareComponent() end

---@return DecalComponent
function SceneNode:getFirstDecalComponent() end

---@return TriggerComponent
function SceneNode:getFirstTriggerComponent() end

---@return FogDensityComponent
function SceneNode:getFirstFogDensityComponent() end

---@return CameraComponent
function SceneNode:getFirstCameraComponent() end

---@return GlobalIlluminationProbeComponent
function SceneNode:getFirstGlobalIlluminationProbeComponent() end

---@return ReflectionProbeComponent
function SceneNode:getFirstReflectionProbeComponent() end

---@return BodyComponent
function SceneNode:getFirstBodyComponent() end

---@return MeshComponent
function SceneNode:getFirstMeshComponent() end

---@return MaterialComponent
function SceneNode:getFirstMaterialComponent() end

---@return SkinComponent
function SceneNode:getFirstSkinComponent() end

---@return SkyboxComponent
function SceneNode:getFirstSkyboxComponent() end

---@return JointComponent
function SceneNode:getFirstJointComponent() end

---@class SceneGraph
SceneGraph = {}

---@param str string
---@return SceneNode
function SceneGraph:newSceneNode(str) end

---@param sceneNode SceneNode
function SceneGraph:setActiveCameraNode(sceneNode) end

---@param str string
---@return SceneNode
function SceneGraph:tryFindSceneNode(str) end

---@class Event
Event = {}

---@return WeakArraySceneNodePtr
function Event:getAssociatedSceneNodes() end

---@class LightEvent
LightEvent = {}

---@param vec4 Vec4
function LightEvent:setIntensityMultiplier(vec4) end

---@param num number
---@param num2 number
function LightEvent:setFrequency(num, num2) end

---@class ScriptEvent
ScriptEvent = {}

---@class JitterMoveEvent
JitterMoveEvent = {}

---@param vec3 Vec3
---@param vec32 Vec3
function JitterMoveEvent:setPositionLimits(vec3, vec32) end

---@class AnimationEvent
AnimationEvent = {}

---@class EventManager
EventManager = {}

---@param num number
---@param num2 number
---@param sceneNode SceneNode
---@return LightEvent
function EventManager:newLightEvent(num, num2, sceneNode) end

---@param num number
---@param num2 number
---@param str string
---@return ScriptEvent
function EventManager:newScriptEvent(num, num2, str) end

---@param num number
---@param num2 number
---@param sceneNode SceneNode
---@return JitterMoveEvent
function EventManager:newJitterMoveEvent(num, num2, sceneNode) end

---@param str string
---@param str2 string
---@param sceneNode SceneNode
---@return AnimationEvent
function EventManager:newAnimationEvent(str, str2, sceneNode) end

---@class Vec2
---@field x number
---@field y number
---@operator add(Vec2): Vec2
---@operator sub(Vec2): Vec2
---@operator mul(Vec2): Vec2
---@operator div(Vec2): Vec2
Vec2 = {}

---@overload fun(): Vec2
---@param num number
---@param num2 number
---@return Vec2
function Vec2.new(num, num2) end

---@param num number
---@param num2 number
function Vec2:setAll(num, num2) end

---@param num number
---@return number
function Vec2:getAt(num) end

---@param num number
---@param num2 number
function Vec2:setAt(num, num2) end

---@param vec2 Vec2
function Vec2:copy(vec2) end

---@return number
function Vec2:length() end

---@return Vec2
function Vec2:normalize() end

---@param vec2 Vec2
---@return number
function Vec2:dot(vec2) end

---@class Vec3
---@field x number
---@field y number
---@field z number
---@operator add(Vec3): Vec3
---@operator sub(Vec3): Vec3
---@operator mul(Vec3): Vec3
---@operator div(Vec3): Vec3
Vec3 = {}

---@overload fun(num: number): Vec3
---@overload fun(): Vec3
---@param num number
---@param num2 number
---@param num3 number
---@return Vec3
function Vec3.new(num, num2, num3) end

---@param num number
---@param num2 number
---@param num3 number
function Vec3:setAll(num, num2, num3) end

---@param num number
---@return number
function Vec3:getAt(num) end

---@param num number
---@param num2 number
function Vec3:setAt(num, num2) end

---@param vec3 Vec3
function Vec3:copy(vec3) end

---@return number
function Vec3:length() end

---@return Vec3
function Vec3:normalize() end

---@param vec3 Vec3
---@return number
function Vec3:dot(vec3) end

---@class Vec4
---@field x number
---@field y number
---@field z number
---@field w number
---@operator add(Vec4): Vec4
---@operator sub(Vec4): Vec4
---@operator mul(Vec4): Vec4
---@operator div(Vec4): Vec4
Vec4 = {}

---@overload fun(num: number): Vec4
---@overload fun(): Vec4
---@param num number
---@param num2 number
---@param num3 number
---@param num4 number
---@return Vec4
function Vec4.new(num, num2, num3, num4) end

---@param num number
---@param num2 number
---@param num3 number
---@param num4 number
function Vec4:setAll(num, num2, num3, num4) end

---@param num number
---@return number
function Vec4:getAt(num) end

---@param num number
---@param num2 number
function Vec4:setAt(num, num2) end

---@param vec4 Vec4
function Vec4:copy(vec4) end

---@return number
function Vec4:length() end

---@return Vec4
function Vec4:normalize() end

---@param vec4 Vec4
---@return number
function Vec4:dot(vec4) end

---@class Mat3
Mat3 = {}

---@overload fun(): Mat3
---@param num number
---@return Mat3
function Mat3.new(num) end

---@param mat3 Mat3
function Mat3:copy(mat3) end

---@param num number
---@param num2 number
---@return number
function Mat3:getAt(num, num2) end

---@param num number
---@param num2 number
---@param num3 number
function Mat3:setAt(num, num2, num3) end

---@param num number
---@param num2 number
---@param num3 number
---@param num4 number
---@param num5 number
---@param num6 number
---@param num7 number
---@param num8 number
---@param num9 number
function Mat3:setAll(num, num2, num3, num4, num5, num6, num7, num8, num9) end

---@class Mat3x4
Mat3x4 = {}

---@overload fun(): Mat3x4
---@param num number
---@return Mat3x4
function Mat3x4.new(num) end

---@param mat3x4 Mat3x4
function Mat3x4:copy(mat3x4) end

---@param num number
---@param num2 number
---@return number
function Mat3x4:getAt(num, num2) end

---@param num number
---@param num2 number
---@param num3 number
function Mat3x4:setAt(num, num2, num3) end

---@param num number
---@param num2 number
---@param num3 number
---@param num4 number
---@param num5 number
---@param num6 number
---@param num7 number
---@param num8 number
---@param num9 number
---@param num10 number
---@param num11 number
---@param num12 number
function Mat3x4:setAll(num, num2, num3, num4, num5, num6, num7, num8, num9, num10, num11, num12) end

---@class Transform
Transform = {}

---@overload fun(): Transform
---@param vec3 Vec3
---@param mat3 Mat3
---@param vec32 Vec3
---@return Transform
function Transform.new(vec3, mat3, vec32) end

---@param transform Transform
function Transform:copy(transform) end

---@return Vec3
function Transform:getOrigin() end

---@param vec3 Vec3
function Transform:setOrigin(vec3) end

---@return Mat3
function Transform:getRotation() end

---@param mat3 Mat3
function Transform:setRotation(mat3) end

---@return Vec3
function Transform:getScale() end

---@param vec3 Vec3
function Transform:setScale(vec3) end

---@class Renderer
Renderer = {}

---@return number
function Renderer:getAspectRatio() end

---@param str string
function Renderer:setCurrentDebugRenderTarget(str) end

---@return SceneGraph
function getSceneGraph() end

---@return EventManager
function getEventManager() end

---@param num number
---@return number
function toRad(num) end

---@param str string
function logi(str) end

---@param str string
function loge(str) end

---@param str string
function logw(str) end

---@param str string
function logv(str) end

---@return Renderer
function getRenderer() end

