#ifndef ANKI_CONFIG_H
#define ANKI_CONFIG_H

#define ANKI_VERSION_MINOR ${ANKI_VERSION_MINOR}
#define ANKI_VERSION_MAJOR ${ANKI_VERSION_MAJOR}
#define ANKI_REVISION ${ANKI_REVISION}
#define ANKI_CPU_${ANKI_CPU}
#define ANKI_MATH_SIMD_${ANKI_MATH_SIMD}
#define ANKI_WINDOW_BACKEND_${ANKI_WINDOW_BACKEND}
#define ANKI_PLATFORM_${ANKI_PLATFORM}

#endif
