// Copyright (C) 2009-present, Panagiotis Christopoulos Charitos and contributors.
// All rights reserved.
// Code licensed under the BSD License.
// http://www.anki3d.org/LICENSE

// An awful trick to instantiate stuff with the resource type

#if !defined(ANKI_INSTANSIATE_RESOURCE_DELIMITER)
#	define ANKI_INSTANSIATE_RESOURCE_DELIMITER()
#endif

ANKI_INSTANTIATE_RESOURCE(AnimationResource)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(ImageResource)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(MeshResource)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(CpuMeshResource)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(SkeletonResource)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(ParticleEmitterResource)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(ModelResource)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(ScriptResource)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(DummyResource)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(GenericResource)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(ImageAtlasResource)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(ShaderProgramResource)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(MaterialResource)

#if defined(ANKI_INSTANTIATE_RESOURCE)
#	undef ANKI_INSTANTIATE_RESOURCE
#endif

#if defined(ANKI_INSTANSIATE_RESOURCE_DELIMITER)
#	undef ANKI_INSTANSIATE_RESOURCE_DELIMITER
#endif
