// Copyright (C) 2009-present, Panagiotis Christopoulos Charitos and contributors.
// All rights reserved.
// Code licensed under the BSD License.
// http://www.anki3d.org/LICENSE

#include <AnKi/Editor/AssetBrowserUi.h>
#include <AnKi/Resource/ImageResource.h>
#include <AnKi/Util/Filesystem.h>

namespace anki {

static const Char* kDefaultMaterial = R"(<!-- This file is generated by the editor -->
<material shadows="1">
	<shaderProgram name="GBufferGeneric">
		<mutation>
			<mutator name="DIFFUSE_TEX" value="0"/>
			<mutator name="SPECULAR_TEX" value="0"/>
			<mutator name="ROUGHNESS_METALNESS_TEX" value="0"/>
			<mutator name="NORMAL_TEX" value="0"/>
			<mutator name="EMISSIVE_TEX" value="0"/>
			<mutator name="ALPHA_TEST" value="0"/>
		</mutation>
	</shaderProgram>

	<inputs>
		<input name="m_diffuseScale" value="0.5 0.5 0.5 1.000000"/>
		<input name="m_specularScale" value="0.04 0.04 0.04"/>
		<input name="m_roughnessScale" value="1.000000"/>
		<input name="m_metalnessScale" value="0.0"/>
		<input name="m_emissionScale" value="0.0 0.0 0.0"/>
		<input name="m_subsurface" value="0.0"/>
	</inputs>
</material>
)";

static const Char* kDefaultParticles = R"(<!-- This file is generated by the editor -->
<particleEmitter>
	<shaderProgram name="GpuParticlesGass" />

	<particleCount value="10"/>
	<emissionPeriod value="0.05"/>
	<particlesPerEmission value="1"/>

	<inputs>
		<input name="m_minParticleLife" value="1"/>
		<input name="m_maxParticleLife" value="2"/>

		<input name="m_minGravityDirection" value="0 1 0"/>
		<input name="m_maxGravityDirection" value="0 1 0"/>
		<input name="m_minGravityMagnitude" value="0.5"/>
		<input name="m_maxGravityMagnitude" value="0.5"/>

		<input name="m_minInitialSize" value="0.78"/>
		<input name="m_maxInitialSize" value="0.82"/>
		<input name="m_minFinalSize" value="0.4"/>
		<input name="m_maxFinalSize" value="0.5"/>

		<input name="m_minInitialAlpha" value="0.5"/>
		<input name="m_maxInitialAlpha" value="1"/>
		<input name="m_minFinalAlpha" value="0"/>
		<input name="m_maxFinalAlpha" value="0"/>

		<input name="m_minStartingPosition" value="0.04 0.1 -0.04"/>
		<input name="m_maxStartingPosition" value="0.04 0.1 0.04"/>
	</inputs>
</particleEmitter>
)";

enum class AssetFileType : U32
{
	kNone,
	kTexture,
	kMaterial,
	kMesh,
	kLua,
	kParticleEmitter,
	kScene
};

class AssetBrowserUi::AssetFile
{
public:
	String m_filename;

	// Absolute path on the actual filesystem. Use it for filesystem operations (rename, tooltips, selection key).
	String m_fullFilepath;

	// Path relative to the data path, as understood by ResourceFilesystem/ResourceManager. Use it to load the resource so the browser shares the
	// engine's resource cache instead of loading the asset a second time.
	String m_resourceFilepath;

	AssetDir* m_parentDir = nullptr;

	AssetFileType m_type = AssetFileType::kNone;

	AssetFile() = default;

	AssetFile(const AssetFile&) = delete;

	AssetFile(AssetFile&& b)
	{
		*this = std::move(b);
	}

	AssetFile& operator=(const AssetFile&) = delete;

	AssetFile& operator=(AssetFile&& b)
	{
		m_filename = std::move(b.m_filename);
		m_fullFilepath = std::move(b.m_fullFilepath);
		m_resourceFilepath = std::move(b.m_resourceFilepath);
		m_type = b.m_type;
		b.m_type = AssetFileType::kNone;
		m_parentDir = std::move(b.m_parentDir);
		return *this;
	}
};

class AssetBrowserUi::AssetDir
{
public:
	String m_dirname;
	String m_fullPath;
	DynamicArray<AssetDir> m_children;
	DynamicArray<AssetFile> m_files;
	AssetDir* m_parentDir = nullptr;
	U32 m_id = 0;

	AssetDir() = default;

	AssetDir(const AssetDir&) = delete;

	AssetDir(AssetDir&& b)
	{
		*this = std::move(b);
	}

	AssetDir& operator=(const AssetDir&) = delete;

	AssetDir& operator=(AssetDir&& b)
	{
		m_dirname = std::move(b.m_dirname);
		m_fullPath = std::move(b.m_fullPath);
		m_children = std::move(b.m_children);
		m_files = std::move(b.m_files);
		m_id = b.m_id;
		b.m_id = 0;
		return *this;
	}
};

class AssetBrowserUi::AssetDirOrFile
{
public:
	union
	{
		const AssetDir* m_dir = nullptr;
		const AssetFile* m_file;
	};
	Bool m_isDir = true;
};

AssetBrowserUi::AssetBrowserUi()
{
	ANKI_CHECKF(ResourceManager::getSingleton().loadResource("EngineAssets/Editor/Material.png", m_materialIcon));
	ANKI_CHECKF(ResourceManager::getSingleton().loadResource("EngineAssets/Editor/Mesh.png", m_meshIcon));
}

AssetBrowserUi::~AssetBrowserUi()
{
}

void AssetBrowserUi::buildAssetStructure(DynamicArray<AssetDir>& dirs)
{
	dirs.destroy();

	U32 id = 0;
	ResourceFilesystem::getSingleton().iterateAllDataPaths([&](CString dataPath) {
		// Create root dir for the data path
		AssetDir& dir = *dirs.emplaceBack();
		dir.m_dirname = dataPath;
		dir.m_fullPath = dataPath;
		dir.m_id = id++;

		ResourceFilesystem::getSingleton().iterateFilenamesInDataPath(dataPath, [&](CString filepath) {
			StringList dirNames;
			dirNames.splitString(filepath, '/');

			// Don't need the file
			const String filename = dirNames.getBack();
			dirNames.popBack();

			// Create the dirs recursively
			AssetDir* crntDir = &dir;
			for(CString dirName : dirNames)
			{
				Bool dirFound = false;
				for(AssetDir& childDir : crntDir->m_children)
				{
					if(childDir.m_dirname == dirName)
					{
						dirFound = true;
						crntDir = &childDir;
						break;
					}
				}

				if(!dirFound)
				{
					AssetDir* newDir = crntDir->m_children.emplaceBack();
					newDir->m_dirname = dirName;
					newDir->m_fullPath = crntDir->m_fullPath + "/" + dirName;
					newDir->m_id = id++;

					crntDir = newDir;
				}
			}

			// Create the file
			const String extension = getFileExtension(filename);
			AssetFileType filetype = AssetFileType::kNone;
			if(extension == "ankitex" || extension == "png")
			{
				filetype = AssetFileType::kTexture;
			}
			else if(extension == "ankimtl")
			{
				filetype = AssetFileType::kMaterial;
			}
			else if(extension == "ankimesh")
			{
				filetype = AssetFileType::kMesh;
			}
			else if(extension == "ankipart")
			{
				filetype = AssetFileType::kParticleEmitter;
			}
			else if(extension == "ankiscene")
			{
				filetype = AssetFileType::kScene;
			}
			else if(extension == "lua")
			{
				filetype = AssetFileType::kLua;
			}

			if(filetype != AssetFileType::kNone)
			{
				// filepath is expected to be relative to the data path. A leading '/' or an empty string would mean
				// it got mixed up with an absolute/full path and would break resource loading below.
				ANKI_ASSERT(!filepath.isEmpty() && filepath[0] != '/');

				AssetFile* file = crntDir->m_files.emplaceBack();
				file->m_fullFilepath = String(dataPath) + "/" + filepath;
				file->m_filename = filename;
				file->m_resourceFilepath = filepath;
				file->m_type = filetype;
			}

			return FunctorContinue::kContinue;
		});

		return FunctorContinue::kContinue;
	});

	for(AssetDir& dir : dirs)
	{
		sortFilesRecursively(dir);
	}

	// Assign parents after all dynamic arrays have settled down
	for(AssetDir& dir : dirs)
	{
		assignParentDirRecursively(dir);
	}
}

void AssetBrowserUi::sortFilesRecursively(AssetDir& root)
{
	std::sort(root.m_files.getBegin(), root.m_files.getEnd(), [](const AssetFile& a, const AssetFile& b) {
		return a.m_filename < b.m_filename;
	});

	std::sort(root.m_children.getBegin(), root.m_children.getEnd(), [](const AssetDir& a, const AssetDir& b) {
		return a.m_dirname < b.m_dirname;
	});

	for(AssetDir& child : root.m_children)
	{
		sortFilesRecursively(child);
	}
}

void AssetBrowserUi::assignParentDirRecursively(AssetDir& root)
{
	for(AssetFile& file : root.m_files)
	{
		file.m_parentDir = &root;
	}

	for(AssetDir& child : root.m_children)
	{
		child.m_parentDir = &root;
		assignParentDirRecursively(child);
	}
}

void AssetBrowserUi::loadImageToCache(CString fname, ImageResourcePtr& img)
{
	// Try to load first
	ANKI_CHECKF(ResourceManager::getSingleton().loadResource(fname, img));

	// Update the cache
	const U32 crntFrame = ImGui::GetFrameCount();
	Bool entryFound = false;
	DynamicArray<ImageCacheEntry>& cache = m_imageCache;
	for(ImageCacheEntry& entry : cache)
	{
		if(entry.m_image->getUuid() == img->getUuid())
		{
			entry.m_lastSeenInFrame = crntFrame;
			entryFound = true;
			break;
		}
	}

	if(!entryFound)
	{
		cache.emplaceBack(ImageCacheEntry{img, crntFrame});
	}

	// Trim the cache: Try to remove stale entries
	const U32 frameInactivityCount = 60 * 30; // ~30"
	while(true)
	{
		Bool foundStaleEntry = false;
		for(auto it = cache.getBegin(); it != cache.getEnd(); ++it)
		{
			ANKI_ASSERT(crntFrame >= it->m_lastSeenInFrame);
			if(crntFrame - it->m_lastSeenInFrame > frameInactivityCount)
			{
				cache.erase(it);
				foundStaleEntry = true;
				break;
			}
		}

		if(!foundStaleEntry)
		{
			break;
		}
	}
}

void AssetBrowserUi::drawWindow(Vec2 initialPosition, Vec2 initialSize, CString resourceToLocate, ImGuiWindowFlags windowFlags)
{
	if(!m_open)
	{
		return;
	}

	if(m_assetPaths.getSize() == 0 || m_refreshAssetsPathsNextTime)
	{
		ANKI_CHECKF(ResourceFilesystem::getSingleton().refreshAll());
		buildAssetStructure(m_assetPaths);
		m_refreshAssetsPathsNextTime = false;
	}

	if(resourceToLocate)
	{
		m_resourceToLocate = resourceToLocate;
		m_rightClickSelectedFilepath.destroy(); // Deselect
		m_showRightClickMenuDialog = false;
		m_framesUntilScrollToLocatedFile = 2;
		m_locatedFileHighlightFramesLeft = kLocatedFileHighlightFrameCount;
	}

	m_runCtx = {};
	setSelectedPointers();

	{
		const Vec2 viewportSize = ImGui::GetMainViewport()->WorkSize;
		const Vec2 initialSize = Vec2(viewportSize.y * 0.75f);
		const Vec2 initialPos = (viewportSize - initialSize) / 2.0f;

		m_imageViewerWindow.drawWindow(initialPos, initialSize, 0);
	}

	{
		const Vec2 viewportSize = ImGui::GetMainViewport()->WorkSize;
		const Vec2 initialSize = Vec2(800.0f, 600.0f);
		const Vec2 initialPos = (viewportSize - initialSize) / 2.0f;

		m_particleEditorWindow.drawWindow(initialPos, initialSize, 0);
	}

	{
		const Vec2 viewportSize = ImGui::GetMainViewport()->WorkSize;
		const Vec2 initialSize = Vec2(800.0f, 600.0f);
		const Vec2 initialPos = (viewportSize - initialSize) / 2.0f;

		m_materialEditorWindow.drawWindow(initialPos, initialSize, 0);
	}

	if(ImGui::GetFrameCount() > 1)
	{
		// Viewport is one frame delay so do that when frame >1
		ImGui::SetNextWindowSize(initialSize, ImGuiCond_FirstUseEver);
		ImGui::SetNextWindowPos(initialPosition, ImGuiCond_FirstUseEver);
	}

	if(ImGui::Begin("Assets", &m_open, windowFlags | ImGuiWindowFlags_MenuBar))
	{
		drawMenu();
		drawToolbox();
		drawDirPath();

		if(ImGui::BeginChild("Icons", Vec2(-1.0f, -1.0f), 0))
		{
			const DynamicArray<AssetDirOrFile> filteredItems = gatherFilteredItems();
			drawIcons(filteredItems);
		}
		ImGui::EndChild();
	}
	ImGui::End();

	rightClickMenuDialog();
}

void AssetBrowserUi::drawToolbox()
{
	// Increase/decrease icon size
	{
		ImGui::TextUnformatted("Icon Size");
		ImGui::SameLine();
		ImGui::SetNextItemWidth(64.0f);
		ImGui::SliderInt("##Icon Size", &m_cellSize, 5, 11, "%d", ImGuiSliderFlags_AlwaysClamp);
		ImGui::SameLine();
	}

	// Refresh tree
	if(ImGui::Button(ICON_MDI_REFRESH))
	{
		m_refreshAssetsPathsNextTime = true;
	}
	ImGui::SameLine();

	// Filter
	drawfilteredText(m_fileFilter);
}

void AssetBrowserUi::drawDirPath()
{
	// Gather dirs from the selected dir to root
	DynamicArray<const AssetDir*> dirsInSelected;
	const AssetDir* crntDir = m_runCtx.m_selectedDir;
	while(crntDir)
	{
		dirsInSelected.emplaceBack(crntDir);
		crntDir = crntDir->m_parentDir;
	}

	// Reverse
	std::reverse(dirsInSelected.getBegin(), dirsInSelected.getEnd());

	// Draw the root button
	if(ImGui::Button(ICON_MDI_FOLDER " /"))
	{
		m_rightClickSelectedFilepath.destroy();
	}

	// Draw the buttons
	for(const AssetDir* dir : dirsInSelected)
	{
		ImGui::SameLine();

		if(ImGui::Button(String().sprintf("%s/", dir->m_dirname.cstr()).cstr()))
		{
			m_selectedDirPath = dir->m_fullPath;
		}
	}
}

void AssetBrowserUi::drawIcons(ConstWeakArray<AssetDirOrFile> filteredItems)
{
	auto dragDropSource = [](auto& file, const Char* identifier) {
		if(ImGui::BeginDragDropSource(ImGuiDragDropFlags_None))
		{
			// Copy the resource path incl. the null terminator; ImGui owns the copy for the drag's duration.
			const CString path = file.m_resourceFilepath;
			ImGui::SetDragDropPayload(identifier, path.cstr(), path.getLength() + 1);

			ImGui::TextUnformatted(file.m_filename.cstr());
			ImGui::EndDragDropSource();
		}
	};

	const F32 cellWidth = F32(m_cellSize) * 16;
	const U32 columnCount = U32(ImGui::GetContentRegionAvail().x / cellWidth);
	ImGui::SetNextItemWidth(-1.0f);
	const ImGuiTableFlags flags = ImGuiTableFlags_SizingStretchSame | ImGuiTableFlags_Resizable | ImGuiTableFlags_BordersOuter
								  | ImGuiTableFlags_BordersV | ImGuiTableFlags_ContextMenuInBody;

	if(filteredItems.getSize() && columnCount && ImGui::BeginTable("Grid", columnCount, flags))
	{
		const U32 rowCount = (filteredItems.getSize() + columnCount - 1) / columnCount;

		for(U32 row = 0; row < rowCount; ++row)
		{
			ImGui::TableNextRow();
			for(U32 column = 0; column < columnCount; ++column)
			{
				ImGui::TableNextColumn();

				// Square icon button that fills the cell minus the horizontal frame padding on both sides
				auto calcIconButtonSize = [] {
					const F32 iconSize = ImGui::GetContentRegionAvail().x - 2.0f * ImGui::GetStyle().FramePadding.x;
					return Vec2(iconSize);
				};

				auto pushFontSize = [&] {
					ImGui::PushFont(nullptr, ImGui::GetContentRegionAvail().x - 12.0f); // Why 12? After trial and error it looks OK
				};

				const U32 idx = row * columnCount + column;
				if(idx < filteredItems.getSize())
				{
					const Bool isDir = filteredItems[idx].m_isDir;
					const AssetFile& file = *((!isDir) ? filteredItems[idx].m_file : nullptr);
					const AssetDir& dir = *((isDir) ? filteredItems[idx].m_dir : nullptr);

					ImGui::PushID(idx);

					if(isDir)
					{
						pushFontSize();
						if(ImGui::Button(ICON_MDI_FOLDER, calcIconButtonSize()))
						{
							m_selectedDirPath = dir.m_fullPath;
						}
						ImGui::PopFont();
					}
					else if(file.m_type == AssetFileType::kMaterial)
					{
						ImTextureID id;
						id.m_texture = &m_materialIcon->getTexture();
						if(ImGui::ImageButton("##", id, calcIconButtonSize()))
						{
							MaterialResourcePtr rsrc;
							ANKI_CHECKF(ResourceManager::getSingleton().loadResource(file.m_resourceFilepath, rsrc));
							m_materialEditorWindow.open(*rsrc);
						}

						dragDropSource(file, kMaterialAssetDragDropPayload);
					}
					else if(file.m_type == AssetFileType::kMesh)
					{
						ImTextureID id;
						id.m_texture = &m_meshIcon->getTexture();
						ImGui::ImageButton("##", id, calcIconButtonSize());

						dragDropSource(file, kMeshAssetDragDropPayload);
					}
					else if(file.m_type == AssetFileType::kTexture)
					{
						ImageResourcePtr img;
						loadImageToCache(file.m_resourceFilepath, img);
						ImTextureID id;
						id.m_texture = &img->getTexture();
						id.m_textureSubresource = TextureSubresourceDesc::all();
						if(ImGui::ImageButton("##", id, calcIconButtonSize()))
						{
							m_imageViewerWindow.m_image = img;
							m_imageViewerWindow.m_open = true;
						}

						dragDropSource(file, kTextureAssetDragDropPayload);
					}
					else if(file.m_type == AssetFileType::kParticleEmitter)
					{
						pushFontSize();
						if(ImGui::Button(ICON_MDI_CREATION, calcIconButtonSize()))
						{
							ParticleEmitterResource2Ptr rsrc;
							ANKI_CHECKF(ResourceManager::getSingleton().loadResource(file.m_resourceFilepath, rsrc));
							m_particleEditorWindow.open(*rsrc);
						}

						ImGui::PopFont();
						dragDropSource(file, kParticleEmitterAssetDragDropPayload);
					}
					else if(file.m_type == AssetFileType::kScene)
					{
						pushFontSize();
						if(ImGui::Button(ICON_MDI_CURTAINS, calcIconButtonSize()))
						{
							Scene* scene = nullptr;
							if(SceneGraph::getSingleton().loadScene(file.m_resourceFilepath, scene))
							{
								ANKI_LOGE("Failed to load scene: %s", file.m_resourceFilepath.cstr());
							}
							else
							{
								SceneGraph::getSingleton().setActiveScene(scene);
							}
						}
						ImGui::PopFont();
					}
					else if(file.m_type == AssetFileType::kLua)
					{
						pushFontSize();
						if(ImGui::Button(ICON_MDI_LANGUAGE_LUA, calcIconButtonSize()))
						{
							ANKI_LOGE("TODO");
						}

						ImGui::PopFont();
						dragDropSource(file, kScriptAssetDragDropPayload);
					}

					ImGui::PopID();

					if(!isDir)
					{
						// Right click
						if(ImGui::IsMouseReleased(ImGuiMouseButton_Right) && ImGui::IsItemHovered())
						{
							m_rightClickSelectedFilepath = file.m_resourceFilepath;
							m_showRightClickMenuDialog = true;
						}

						// Scroll to located file
						if(m_runCtx.m_fileToLocate && m_runCtx.m_fileToLocate == &file && m_framesUntilScrollToLocatedFile >= 0)
						{
							if(m_framesUntilScrollToLocatedFile == 0)
							{
								ImGui::SetScrollHereY(0.5f);
							}

							--m_framesUntilScrollToLocatedFile;
						}

						// Color the located file to be more pronounced. The countdown is ticked once per frame in setSelectedPointers()
						if(m_runCtx.m_fileToLocate && m_runCtx.m_fileToLocate == &file && m_locatedFileHighlightFramesLeft > 0)
						{
							const F32 factor = F32(m_locatedFileHighlightFramesLeft) / F32(kLocatedFileHighlightFrameCount);

							Vec4 col = ImGui::GetStyleColorVec4(ImGuiCol_NavCursor);
							col.w *= factor; // fade the alpha, not the hue
							ImGui::TableSetBgColor(ImGuiTableBgTarget_CellBg, ImGui::GetColorU32(col));
						}

						ImGui::TextWrapped("%s", file.m_filename.cstr());

						ImGui::SetItemTooltip("%s", file.m_fullFilepath.cstr());
					}
					else
					{
						ImGui::TextWrapped("%s", dir.m_dirname.cstr());
						ImGui::SetItemTooltip("%s", dir.m_fullPath.cstr());
					}
				}
			}
		}

		ImGui::EndTable();
	}
	else
	{
		ImGui::TextUnformatted("Empty");
	}
}

void AssetBrowserUi::rightClickMenuDialog()
{
	const AssetFile* selectedFile = m_runCtx.m_rightClickSelectedFile;
	if(!selectedFile)
	{
		return;
	}

	if(m_showRightClickMenuDialog)
	{
		ImGui::OpenPopup("Right Click");
		m_showRightClickMenuDialog = false;
	}

	if(ImGui::BeginPopup("Right Click"))
	{
		// Delete file
		if(ImGui::Button(ICON_MDI_DELETE_FOREVER " Delete"))
		{
			if(removeFile(selectedFile->m_fullFilepath))
			{
				ANKI_LOGE("Failed to remove file: %s", selectedFile->m_fullFilepath.cstr());
			}

			m_refreshAssetsPathsNextTime = true;
			ImGui::CloseCurrentPopup();
		}

		// Rename file
		Array<Char, kMaxTextInputLen> name;
		strncpy(name.getBegin(), selectedFile->m_filename.cstr(), name.getSize());
		name[name.getSize() - 1] = '\0'; // strncpy doesn't null-terminate if the source doesn't fit
		if(ImGui::InputText("Rename", name.getBegin(), name.getSize(), ImGuiInputTextFlags_EnterReturnsTrue))
		{
			CString newName(name.getBegin());
			if(newName.getLength())
			{
				String newFilepath = getParentFilepath(selectedFile->m_fullFilepath);
				newFilepath += "/";
				newFilepath += newName;

				ANKI_LOGV("Will rename %s to %s", selectedFile->m_fullFilepath.cstr(), newFilepath.cstr());
				if(renameFile(selectedFile->m_fullFilepath, newFilepath))
				{
					ANKI_LOGE("Renaming failed");
				}
				else
				{
					m_refreshAssetsPathsNextTime = true;
					m_rightClickSelectedFilepath.destroy();
				}
			}
		}

		ImGui::EndPopup();
	}
	else
	{
		// Diselect the file
		m_rightClickSelectedFilepath.destroy();
	}
}

void AssetBrowserUi::drawMenu()
{
	auto createNewFile = [this](CString suffix, CString fileText) {
		U32 index = 0;

		while(index < 10)
		{
			String filepath;
			filepath.sprintf("%s/%04u.%s", m_runCtx.m_selectedDir->m_fullPath.cstr(), index, suffix.cstr());

			if(!fileExists(filepath))
			{
				File file;
				Error err = file.open(filepath, FileOpenFlag::kWrite);
				if(!err)
				{
					err = file.writeText(fileText);
				}

				if(err)
				{
					ANKI_LOGE("Failed to create new file: %s", filepath.cstr());
				}

				break;
			}

			++index;
		}

		if(index == 10)
		{
			ANKI_LOGE("Failed to create file: %s", suffix.cstr());
		}
	};

	if(ImGui::BeginMenuBar())
	{
		ImGui::BeginDisabled(m_runCtx.m_selectedDir == nullptr);

		if(ImGui::BeginMenu(ICON_MDI_PLUS_BOX " New"))
		{
			if(ImGui::MenuItem(ICON_MDI_TEXTURE_BOX " Material"))
			{
				createNewFile("NewMaterial.ankimtl", kDefaultMaterial);
				m_refreshAssetsPathsNextTime = true;
			}

			if(ImGui::MenuItem(ICON_MDI_CREATION " Particles"))
			{
				createNewFile("NewParticles.ankipart", kDefaultParticles);
				m_refreshAssetsPathsNextTime = true;
			}

			if(ImGui::MenuItem(ICON_MDI_CURTAINS " Scene"))
			{
				U32 index = 0;
				while(index < 10)
				{
					String filepath;
					filepath.sprintf("%s/%04u.NewScene.ankiscene", m_runCtx.m_selectedDir->m_fullPath.cstr(), index);

					if(!fileExists(filepath))
					{
						String randomSceneName;
						randomSceneName.sprintf("%u", U32(getRandom() % kMaxU32));
						Scene* tempScene = SceneGraph::getSingleton().newEmptyScene(randomSceneName);
						tempScene->setCanBeSaved(true);

						if(SceneGraph::getSingleton().saveScene(filepath, *tempScene))
						{
							ANKI_LOGE("Failed to create new scene: %s", filepath.cstr());
						}

						SceneGraph::getSingleton().deleteScene(tempScene);
						break;
					}

					++index;
				}

				if(index == 10)
				{
					ANKI_LOGE("Failed to create scene");
				}

				m_refreshAssetsPathsNextTime = true;
			}

			ImGui::EndMenu();
		}

		ImGui::EndDisabled();

		if(ImGui::BeginMenu(ICON_MDI_IMPORT " Import"))
		{
			// TODO
			ImGui::EndMenu();
		}

		ImGui::EndMenuBar();
	}
}

template<typename TFunc, typename TFunc2>
FunctorContinue AssetBrowserUi::visitTree(AssetDir& dir, TFunc dirFunc, TFunc2 fileFunc)
{
	FunctorContinue cont = FunctorContinue::kContinue;

	cont = dirFunc(dir);

	for(AssetFile& file : dir.m_files)
	{
		cont = fileFunc(file);
		if(cont == FunctorContinue::kStop)
		{
			break;
		}
	}

	if(cont == FunctorContinue::kContinue)
	{
		for(AssetDir& child : dir.m_children)
		{
			cont = visitTree(child, dirFunc, fileFunc);
			if(cont == FunctorContinue::kStop)
			{
				break;
			}
		}
	}

	return cont;
}

void AssetBrowserUi::setSelectedPointers()
{
	for(AssetDir& rootDir : m_assetPaths)
	{
		visitTree(
			rootDir,
			[this](AssetDir& dir) {
				if(dir.m_fullPath == m_selectedDirPath)
				{
					m_runCtx.m_selectedDir = &dir;
				}
				return FunctorContinue::kContinue;
			},
			[this](AssetFile& file) {
				if(file.m_resourceFilepath == m_rightClickSelectedFilepath)
				{
					m_runCtx.m_rightClickSelectedFile = &file;
				}

				if(file.m_resourceFilepath == m_resourceToLocate)
				{
					m_runCtx.m_fileToLocate = &file;
				}

				return FunctorContinue::kContinue;
			});
	}

	if(m_runCtx.m_selectedDir == nullptr)
	{
		m_selectedDirPath.destroy();
	}

	if(m_runCtx.m_rightClickSelectedFile == nullptr)
	{
		m_rightClickSelectedFilepath.destroy();
	}

	if(m_runCtx.m_fileToLocate == nullptr)
	{
		m_resourceToLocate.destroy();
	}
	else if(m_locatedFileHighlightFramesLeft > 0)
	{
		// Tick the highlight per frame, not per cell draw, so it counts down even when the located file is scrolled out of view
		--m_locatedFileHighlightFramesLeft;
		if(m_locatedFileHighlightFramesLeft == 0)
		{
			m_resourceToLocate.destroy(); // Done highlighting, forget the located resource
		}
	}

	// Change directory if there is a file to be located
	if(m_runCtx.m_fileToLocate && m_framesUntilScrollToLocatedFile > 0)
	{
		m_runCtx.m_selectedDir = m_runCtx.m_fileToLocate->m_parentDir;
		m_selectedDirPath = m_runCtx.m_fileToLocate->m_parentDir->m_fullPath;
	}
}

DynamicArray<AssetBrowserUi::AssetDirOrFile> AssetBrowserUi::gatherFilteredItems()
{
	DynamicArray<AssetDirOrFile> arr;

	if(!m_runCtx.m_selectedDir)
	{
		// Gather root directories
		for(const AssetDir& dir : m_assetPaths)
		{
			if(m_fileFilter.PassFilter(dir.m_dirname.cstr()))
			{
				const AssetDirOrFile item{.m_dir = &dir, .m_isDir = true};
				arr.emplaceBack(item);
			}
		}
	}
	else
	{
		// Gather directories
		for(const AssetDir& dir : m_runCtx.m_selectedDir->m_children)
		{
			if(m_fileFilter.PassFilter(dir.m_dirname.cstr()))
			{
				const AssetDirOrFile item{.m_dir = &dir, .m_isDir = true};
				arr.emplaceBack(item);
			}
		}

		// Use the filter to gather the files
		for(const AssetFile& f : m_runCtx.m_selectedDir->m_files)
		{
			if(m_fileFilter.PassFilter(f.m_filename.cstr()))
			{
				const AssetDirOrFile item{.m_file = &f, .m_isDir = false};
				arr.emplaceBack(item);
			}
		}
	}

	return arr;
}

} // end namespace anki
