#ifndef ANKI_CONFIG_H
#define ANKI_CONFIG_H

#define ANKI_VERSION_MINOR ${ANKI_VERSION_MINOR}
#define ANKI_VERSION_MAJOR ${ANKI_VERSION_MAJOR}
#define ANKI_REVISION ${ANKI_REVISION}
#define ANKI_MATH_SIMD_${ANKI_MATH_SIMD} 1
#define ANKI_WINDOW_BACKEND_${ANKI_WINDOW_BACKEND} 1

#endif
