// Copyright (C) 2009-present, Panagiotis Christopoulos Charitos and contributors.
// All rights reserved.
// Code licensed under the BSD License.
// http://www.anki3d.org/LICENSE

#if !defined(ANKI_SCENE_COMPONENT_SEPARATOR)
#	define ANKI_SCENE_COMPONENT_SEPARATOR
#endif

// ANKI_DEFINE_SCENE_COMPONENT(className, weight, sceneNodeCanHaveMany, icon, serializable, canBeDeleted)

ANKI_DEFINE_SCENE_COMPONENT(Script, 0.0f, true, LANGUAGE_LUA, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Body, 10.0f, false, CUBE_SEND, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(PlayerController, 10.0f, false, HUMAN, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Move, 30.0f, false, AXIS_ARROW, false, false)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Skin, 30.0f, false, BONE, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Joint, 35.0f, true, CONNECTION, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Trigger, 40.0f, true, LIGHT_SWITCH_OFF, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Mesh, 50.0f, false, VECTOR_POLYGON, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(ParticleEmitter2, 60.0f, false, CREATION, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Material, 100.0f, true, TEXTURE_BOX, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Decal, 100.0f, false, LIQUID_SPOT, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Camera, 100.0f, false, CAMERA, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(FogDensity, 100.0f, false, CLOUD, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(GlobalIlluminationProbe, 100.0f, false, SPHERE, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(ReflectionProbe, 100.0f, false, SPHERE, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Skybox, 100.0f, false, EARTH, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Ui, 100.0f, true, WINDOW_RESTORE, false, true)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(LensFlare, 100.0f, true, FLARE, true, true)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Light, 100.0f, false, LIGHTBULB, true, true)

#undef ANKI_DEFINE_SCENE_COMPONENT
#undef ANKI_SCENE_COMPONENT_SEPARATOR
