// Copyright (C) 2009-present, Panagiotis Christopoulos Charitos and contributors.
// All rights reserved.
// Code licensed under the BSD License.
// http://www.anki3d.org/LICENSE

#if !defined(ANKI_SCENE_COMPONENT_SEPARATOR)
#	define ANKI_SCENE_COMPONENT_SEPARATOR
#endif

// ANKI_DEFINE_SCENE_COMPONENT(className, weight, sceneNodeCanHaveMany, icon)

ANKI_DEFINE_SCENE_COMPONENT(Script, 0.0f, true, LANGUAGE_LUA)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Body, 10.0f, false, CUBE_SEND)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(PlayerController, 10.0f, false, HUMAN)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Move, 30.0f, false, AXIS_ARROW)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Skin, 30.0f, false, BONE)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Joint, 35.0f, true, CONNECTION)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Trigger, 40.0f, true, LIGHT_SWITCH_OFF)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Mesh, 50.0f, false, VECTOR_POLYGON)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(ParticleEmitter2, 60.0f, false, CREATION)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Material, 100.0f, true, TEXTURE_BOX)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(ParticleEmitter, 100.0f, false, CREATION)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Decal, 100.0f, false, LIQUID_SPOT)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Camera, 100.0f, false, CAMERA)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(FogDensity, 100.0f, false, CLOUD)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(GlobalIlluminationProbe, 100.0f, false, SPHERE)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(ReflectionProbe, 100.0f, false, SPHERE)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Skybox, 100.0f, false, EARTH)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Ui, 100.0f, true, WINDOW_RESTORE)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(LensFlare, 100.0f, true, FLARE)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Light, 100.0f, false, LIGHTBULB)

#undef ANKI_DEFINE_SCENE_COMPONENT
#undef ANKI_SCENE_COMPONENT_SEPARATOR
