// Copyright (C) 2009-present, Panagiotis Christopoulos Charitos and contributors.
// All rights reserved.
// Code licensed under the BSD License.
// http://www.anki3d.org/LICENSE

#if !defined(ANKI_SCENE_COMPONENT_SEPARATOR)
#	define ANKI_SCENE_COMPONENT_SEPARATOR
#endif

ANKI_DEFINE_SCENE_COMPONENT(Script, 0.0f, LANGUAGE_LUA)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Body, 10.0f, CUBE_SEND)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(PlayerController, 10.0f, HUMAN)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Move, 30.0f, AXIS_ARROW)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Skin, 30.0f, BONE)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Joint, 35.0f, CONNECTION)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Trigger, 40.0f, LIGHT_SWITCH_OFF)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Mesh, 50.0f, VECTOR_POLYGON)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(ParticleEmitter2, 60.0f, FOUNTAIN)
ANKI_SCENE_COMPONENT_SEPARATOR

ANKI_DEFINE_SCENE_COMPONENT(Material, 100.0f, TEXTURE_BOX)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(ParticleEmitter, 100.0f, FOUNTAIN)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Decal, 100.0f, LIQUID_SPOT)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Camera, 100.0f, CAMERA)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(FogDensity, 100.0f, CLOUD)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(GlobalIlluminationProbe, 100.0f, SPHERE)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(ReflectionProbe, 100.0f, SPHERE)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Skybox, 100.0f, EARTH)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Ui, 100.0f, WINDOW_RESTORE)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(LensFlare, 100.0f, FLARE)
ANKI_SCENE_COMPONENT_SEPARATOR
ANKI_DEFINE_SCENE_COMPONENT(Light, 100.0f, LIGHTBULB)

#undef ANKI_DEFINE_SCENE_COMPONENT
#undef ANKI_SCENE_COMPONENT_SEPARATOR
