#ifndef ANKI_SHADERS_COMMON_FRAG_GLSL
#define ANKI_SHADERS_COMMON_FRAG_GLSL

#ifndef DEFAULT_FLOAT_PRECISION
#define DEFAULT_FLOAT_PRECISION highp
#endif

#ifndef DEFAULT_INT_PRECISION
#define DEFAULT_INT_PRECISION highp
#endif

precision DEFAULT_FLOAT_PRECISION float;
precision DEFAULT_FLOAT_PRECISION int;

#endif
