// Copyright (C) 2009-2020, Panagiotis Christopoulos Charitos and contributors.
// All rights reserved.
// Code licensed under the BSD License.
// http://www.anki3d.org/LICENSE

// An awful trick to instantiate stuff with the graphics object type

ANKI_INSTANTIATE_GR_OBJECT(Buffer)
ANKI_INSTANTIATE_GR_OBJECT_DELIMITER()
ANKI_INSTANTIATE_GR_OBJECT(CommandBuffer)
ANKI_INSTANTIATE_GR_OBJECT_DELIMITER()
ANKI_INSTANTIATE_GR_OBJECT(Fence)
ANKI_INSTANTIATE_GR_OBJECT_DELIMITER()
ANKI_INSTANTIATE_GR_OBJECT(Framebuffer)
ANKI_INSTANTIATE_GR_OBJECT_DELIMITER()
ANKI_INSTANTIATE_GR_OBJECT(OcclusionQuery)
ANKI_INSTANTIATE_GR_OBJECT_DELIMITER()
ANKI_INSTANTIATE_GR_OBJECT(TimestampQuery)
ANKI_INSTANTIATE_GR_OBJECT_DELIMITER()
ANKI_INSTANTIATE_GR_OBJECT(Sampler)
ANKI_INSTANTIATE_GR_OBJECT_DELIMITER()
ANKI_INSTANTIATE_GR_OBJECT(Shader)
ANKI_INSTANTIATE_GR_OBJECT_DELIMITER()
ANKI_INSTANTIATE_GR_OBJECT(ShaderProgram)
ANKI_INSTANTIATE_GR_OBJECT_DELIMITER()
ANKI_INSTANTIATE_GR_OBJECT(Texture)
ANKI_INSTANTIATE_GR_OBJECT_DELIMITER()
ANKI_INSTANTIATE_GR_OBJECT(TextureView)
ANKI_INSTANTIATE_GR_OBJECT_DELIMITER()
ANKI_INSTANTIATE_GR_OBJECT(AccelerationStructure)
