// Copyright (C) 2009-2018, Panagiotis Christopoulos Charitos and contributors.
// All rights reserved.
// Code licensed under the BSD License.
// http://www.anki3d.org/LICENSE

// An awful trick to instantiate stuff with the resource type

ANKI_INSTANTIATE_RESOURCE(AnimationResource, AnimationResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(TextureResource, TextureResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(MaterialResource, MaterialResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(MeshResource, MeshResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(SkeletonResource, SkeletonResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(ParticleEmitterResource, ParticleEmitterResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(ModelResource, ModelResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(ScriptResource, ScriptResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(DummyResource, DummyResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(CollisionResource, CollisionResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(GenericResource, GenericResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(TextureAtlasResource, TextureAtlasResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(ShaderProgramResource, ShaderProgramResourcePtr)