// Copyright (C) 2009-2017, Panagiotis Christopoulos Charitos and contributors.
// All rights reserved.
// Code licensed under the BSD License.
// http://www.anki3d.org/LICENSE

// An awful trick to instantiate stuff with the resource type

ANKI_INSTANTIATE_RESOURCE(Animation, AnimationResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(TextureResource, TextureResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(Material, MaterialResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(Mesh, MeshResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(Skeleton, SkeletonResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(ParticleEmitterResource, ParticleEmitterResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(Model, ModelResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(Script, ScriptResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(DummyRsrc, DummyResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(CollisionResource, CollisionResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(GenericResource, GenericResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(TextureAtlas, TextureAtlasResourcePtr)
ANKI_INSTANSIATE_RESOURCE_DELIMITER()
ANKI_INSTANTIATE_RESOURCE(ShaderProgramResource, ShaderProgramResourcePtr)